services:
  web:
    container_name: api_chat
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mysql
    restart: always
    networks:
      - web_api

  mysql:
    image: mysql:8.0
    container_name: mysql_api_chat
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=mysql
      - MYSQL_USER=mysql
      - MYSQL_DATABASE=api_chat_db
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - web_api

networks:
  web_api:
    driver: bridge

volumes:
  mysqldata:
    external: false