server:
  AppVersion: 1.0.0
  Port: :5000
  Domain: localhost
  Mode: Development
  ServerName: api_v1
  PrefixPath: /api/v1
  Registration: true
  SessionLifeTimeMin: 10

ssl:
  Active: true
  CrtPath: certs/localhost.crt
  KeyPath: certs/localhost.key

database:
  Driver: psql
  # Driver: mysql
  CleanStart: false
  CreateAdmin: false

postgres:
  PostgresqlHost: 192.168.48.128
  PostgresqlPort: 5433
  PostgresqlUser: postgres
  PostgresqlPass: postgres
  PostgresqlDB: api_chat_db

mysql:
  MysqlHost: 192.168.48.128
  MysqlPort: 3305
  MysqlUser: mysql
  MysqlPass: mysql
  MysqlDB: api_chat_db

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

admin:
  username: admin
  password: admin
