server:
  AppVersion: 1.0.0
  Port: :5000
  ServerName: api_v1
  PrefixPath: /api/v1
  Registration: true
  SessionLifeTimeMin: 10

ssl:
  Active: true
  # Domain: localhost
  CrtPath: certs/localhost.crt
  KeyPath: certs/localhost.key

database:
  Driver: psql
  # Driver: mysql
  CleanStart: false
  CreateAdmin: true

postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPass: postgres
  PostgresqlDB: api_chat_db

mysql:
  MysqlHost: mysql
  MysqlPort: 3306
  MysqlUser: mysql
  MysqlPass: mysql
  MysqlDB: api_chat_db

logger:
  Development: false
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

admin:
  username: admin
  password: admin